name: multilingual-toxic-nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - transformers=4.40.1
  - datasets=2.18.0
  - scikit-learn=1.3.2
  - pandas=2.2.1
  - numpy=1.26.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - pytorch=2.2.2
  - tqdm=4.66.2
  - jupyterlab=4.1.5
